
baseURL: "https://pdpostojna.si"
googleAnalytics: "UA-132431198-1"
languageCode: "en-us"
title: "Planinsko društvo Postojna"
theme: "beautifulhugo"
metaDataFormat: "yaml"

params:
    homeTitle: "PD Postojna"
    subtitle: "Novice in informacije"
    logo: "img/pd_postojna_logo.png"
    favicon: "img/pd_postojna_logo.png"

menu:
  main:
    - name: "Dodatne Informacije"
      url: "dodatne_informacije"
      weight: 10

    - name: "Načrt izletov"
      identifier: "izleti"
      url: "#"
      weight: 100

    - name: "Splošna navodila"
      parent: "izleti"
      url: "splosna_navodila/"
      weight: 101

    - name: "2020"
      parent: "izleti"
      url: "nacrt_izletov/2020"
      weight: 197

    - name: "2019"
      parent: "izleti"
      url: "nacrt_izletov/2019"
      weight: 198

    - name: "2018"
      parent: "izleti"
      url: "nacrt_izletov/2018"
      weight: 199

    - name: "Pomagajo nam"
      identifier: "sponzorji"
      url: "pomagajo_nam"
      weight: 200

    - name: "Arhiv"
      url: "tags"
      weight: 300
